; Sample configuration file for UnitCheck
;
;
; @author Sven Schrodt<sven@schrodt.club>
; @link https://github.com/SchrodtSven/UnitCheck
; @package UnitCheck
; @version 0.1
; @since since = 2026-03-23

[main]
verboseMessages = true
showColours = true
detectCoverage = false
checkDir = "./check"
haltOnError = false

[logging]
logMessages = false
cliLog = false
xmlLog = false
htmlLog= false
jsonLog = false
filePath = "./tmp/log/"

[meta]
version = "0.1"
author = "Sven Schrodt<sven@schrodt.club>"
gitUrl = "https://github.com/SchrodtSven/UnitCheck"
phpVersion = "8.2+"
since = "2026-03-23"
created = "2026-03-23"
modified = "2026-03-27"
